{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "11b117be",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "\n",
    "# ----------------------------\n",
    "# 1. อ่านภาพ\n",
    "# ----------------------------\n",
    "img = cv2.imread(\"rice.jpg\")\n",
    "if img is None:\n",
    "    print(\"Image not found\")\n",
    "    exit()\n",
    "\n",
    "original = img.copy()\n",
    "\n",
    "# ----------------------------\n",
    "# 2. White Balance\n",
    "# ----------------------------\n",
    "lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)\n",
    "l,a,b = cv2.split(lab)\n",
    "\n",
    "l = l.astype(np.float32)\n",
    "a = a.astype(np.float32)\n",
    "b = b.astype(np.float32)\n",
    "\n",
    "avg_a = np.mean(a)\n",
    "avg_b = np.mean(b)\n",
    "\n",
    "a -= ((avg_a - 128) * (l / 255.0) * 1.1)\n",
    "b -= ((avg_b - 128) * (l / 255.0) * 1.1)\n",
    "\n",
    "lab = cv2.merge([\n",
    "    np.clip(l,0,255).astype(np.uint8),\n",
    "    np.clip(a,0,255).astype(np.uint8),\n",
    "    np.clip(b,0,255).astype(np.uint8)\n",
    "])\n",
    "\n",
    "img = cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)\n",
    "\n",
    "# ----------------------------\n",
    "# 3. Gray + CLAHE + Bilateral\n",
    "# ----------------------------\n",
    "gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)\n",
    "\n",
    "clahe = cv2.createCLAHE(2.0,(8,8))\n",
    "gray = clahe.apply(gray)\n",
    "\n",
    "blur = cv2.bilateralFilter(gray,9,75,75)\n",
    "\n",
    "# ----------------------------\n",
    "# 4. Threshold\n",
    "# ----------------------------\n",
    "thresh = cv2.adaptiveThreshold(\n",
    "    blur,255,\n",
    "    cv2.ADAPTIVE_THRESH_GAUSSIAN_C,\n",
    "    cv2.THRESH_BINARY_INV,\n",
    "    51,2\n",
    ")\n",
    "\n",
    "# ----------------------------\n",
    "# 5. Morphology\n",
    "# ----------------------------\n",
    "kernel = np.ones((3,3),np.uint8)\n",
    "opening = cv2.morphologyEx(thresh,cv2.MORPH_OPEN,kernel,2)\n",
    "sure_bg = cv2.dilate(opening,kernel,3)\n",
    "\n",
    "# ----------------------------\n",
    "# 6. Distance transform\n",
    "# ----------------------------\n",
    "dist = cv2.distanceTransform(opening,cv2.DIST_L2,5)\n",
    "_, sure_fg = cv2.threshold(dist,0.4*dist.max(),255,0)\n",
    "\n",
    "sure_fg = np.uint8(sure_fg)\n",
    "unknown = cv2.subtract(sure_bg,sure_fg)\n",
    "\n",
    "# ----------------------------\n",
    "# 7. Watershed\n",
    "# ----------------------------\n",
    "_, markers = cv2.connectedComponents(sure_fg)\n",
    "markers += 1\n",
    "markers[unknown==255] = 0\n",
    "markers = cv2.watershed(original,markers)\n",
    "\n",
    "# ----------------------------\n",
    "# 8. HSV สำหรับตรวจสีเสีย\n",
    "# ----------------------------\n",
    "hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)\n",
    "\n",
    "lower_yellow = np.array([18,40,120])\n",
    "upper_yellow = np.array([40,255,255])\n",
    "yellow_mask = cv2.inRange(hsv, lower_yellow, upper_yellow)\n",
    "\n",
    "# ----------------------------\n",
    "# 9. Counters\n",
    "# ----------------------------\n",
    "good = 0\n",
    "broken = 0\n",
    "spoiled = 0\n",
    "foreign = 0\n",
    "\n",
    "# ----------------------------\n",
    "# 10. วิเคราะห์แต่ละเมล็ด\n",
    "# ----------------------------\n",
    "for label in np.unique(markers):\n",
    "\n",
    "    if label <= 1:\n",
    "        continue\n",
    "\n",
    "    mask = np.zeros(gray.shape,dtype=\"uint8\")\n",
    "    mask[markers==label] = 255\n",
    "\n",
    "    contours,_ = cv2.findContours(\n",
    "        mask,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE\n",
    "    )\n",
    "\n",
    "    if not contours:\n",
    "        continue\n",
    "\n",
    "    c = max(contours,key=cv2.contourArea)\n",
    "    area = cv2.contourArea(c)\n",
    "\n",
    "    if area < 120 or area > 8000:\n",
    "        continue\n",
    "\n",
    "    x,y,w,h = cv2.boundingRect(c)\n",
    "\n",
    "    # ---- Shape features ----\n",
    "    ratio = w/float(h)\n",
    "    peri = cv2.arcLength(c,True)\n",
    "    circularity = 4*np.pi*area/(peri*peri+1e-5)\n",
    "\n",
    "    # ---- สีผิดปกติ ----\n",
    "    region = yellow_mask[y:y+h,x:x+w]\n",
    "    yellow_ratio = cv2.countNonZero(region)/(w*h+1e-5)\n",
    "\n",
    "    label_text = \"Good\"\n",
    "    color = (0,255,0)\n",
    "\n",
    "    # แตก\n",
    "    if area < 350:\n",
    "        label_text=\"Broken\"\n",
    "        color=(0,0,255)\n",
    "        broken+=1\n",
    "\n",
    "    # สีเสีย\n",
    "    elif yellow_ratio > 0.12:\n",
    "        label_text=\"Spoiled\"\n",
    "        color=(0,0,255)\n",
    "        spoiled+=1\n",
    "\n",
    "    # กลมเกิน = สิ่งแปลกปลอม\n",
    "    elif circularity > 0.7:\n",
    "        label_text=\"Foreign\"\n",
    "        color=(255,0,0)\n",
    "        foreign+=1\n",
    "\n",
    "    else:\n",
    "        good+=1\n",
    "\n",
    "    cv2.rectangle(original,(x,y),(x+w,y+h),color,2)\n",
    "    cv2.putText(original,label_text,(x,y-5),\n",
    "                cv2.FONT_HERSHEY_SIMPLEX,0.5,color,2)\n",
    "\n",
    "# ----------------------------\n",
    "# 11. Overlay dashboard\n",
    "# ----------------------------\n",
    "total = good+broken+spoiled+foreign\n",
    "quality = (good/total)*100 if total>0 else 0\n",
    "\n",
    "cv2.rectangle(original,(0,0),(420,120),(0,0,0),-1)\n",
    "\n",
    "cv2.putText(original,f\"Good: {good}\",(10,25),\n",
    "            cv2.FONT_HERSHEY_SIMPLEX,0.6,(0,255,0),2)\n",
    "\n",
    "cv2.putText(original,f\"Broken: {broken}\",(10,50),\n",
    "            cv2.FONT_HERSHEY_SIMPLEX,0.6,(0,0,255),2)\n",
    "\n",
    "cv2.putText(original,f\"Spoiled: {spoiled}\",(10,75),\n",
    "            cv2.FONT_HERSHEY_SIMPLEX,0.6,(0,0,255),2)\n",
    "\n",
    "cv2.putText(original,f\"Foreign: {foreign}\",(10,100),\n",
    "            cv2.FONT_HERSHEY_SIMPLEX,0.6,(255,0,0),2)\n",
    "\n",
    "cv2.putText(original,f\"Quality: {quality:.1f}%\",(220,60),\n",
    "            cv2.FONT_HERSHEY_SIMPLEX,0.7,(0,255,255),2)\n",
    "\n",
    "# ----------------------------\n",
    "# 12. Show result\n",
    "# ----------------------------\n",
    "cv2.imshow(\"Rice Quality Inspection\",original)\n",
    "cv2.imshow(\"Thresh\",thresh)\n",
    "cv2.imshow(\"Yellow mask\",yellow_mask)\n",
    "\n",
    "cv2.waitKey(0)\n",
    "cv2.destroyAllWindows()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "DeepLearning",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
